var NAMES = [
    "Donnager",
    "Pinus Contorta",
    "Tachi",
    "Scipio Africanus",
    "Limiting Factor",
    "Little Rascal",
    "Gunboat Diplomat",
    "Sirenum Scopuli",
    "Don Quixote",
    "International House of Pancakes",
    "Miguel de Cervantes",
    "Fatherly Instinct",
    "Exercise For The Reader",
    "Komrade Kat",
    "Pierre-Simon Laplace",
    "Joseph-Louis Lagrange",
    "Sound of Silence",
    "Null Hypothesis",
    "Maxwell's Demon",
    "New Mombasa",
    "Shadow of Intent",
    "Long Night of Solace",
    "In Amber Clad",
    "Medium Rare",
    "Silkworm",
    "King Cobra",
    "Roberta Draper",
    "Grace Hopper",
    "Iain M. Banks",
    "James S.A. Corey",
    "Peter Parker's Pizza Palace",
    "Agatha King",
    "Arboghast",
    "Wraith",
    "Karl Marx",
    "Immanuel Kant",
    "Divine Intervention",
    "Divine Inspiration",
    "Hedgeclippers of Consequence",
    "Get Off My Lawn",
    "Prime Mover",
    "Anubis",
    "Hammurabi",
    "Scirocco",
    "Rocinante",
    "Eggs Over Easy",
    "Jiminez",
    "Deep Impact",
    "Independence",
    "Communist Manifesto",
    "Friedrich Engel",
    "Acclamator",
    "Venator",
    "Providence",
    "Ambedkar",
    "Avalanche",
    "Damascus",
    "Iceni",
    "Kittur Chennamma",
    "Morrigan",
    "Shandian",
    "Iniquity",
    "Conviction",
    "Transgression",
    "Dulcinea",
    "Sancho",
    "Babylon"
];

var DEBRIS_NAMES = [
    "Slusher",
    "Alpha",
    "Beta",
    "Charlie",
    "Coffeebean",
    "Prius",
    "Horace",
    "Bryan",
    "Bob",
    "Garbanzo",
    "Indigo",
    "Soccer",
    "Beanie",
    "Fujitsu",
    "Octagon",
    "Python",
    "Shoemaker",
    "Spider",
    "Epsilon",
    "Delta",
    "Gamma",
    "Yocta",
    "Hexagon",
    "Beekeeper",
    "Albert",
    "Samantha",
    "Tricycle",
    "Parmesan",
    "Rose",
    "Sunflower",
    "Snoopy",
    "Lightning",
    "Industry",
    "Sand",
    "Hunter",
    "Fox",
    "Rabbit",
    "Kangaroo",
    "Crowbar",
    "Jackhammer",
    "Longbow",
    "Greatsword",
    "Hotstopper",
    "Mighty",
    "Pico",
    "Spearman",
    "Cavalry",
    "Sincere",
    "Guilty",
    "Snowman",
    "Camero",
    "Fenton",
    "Bepis",
    "Evergreen",
    "Nissan",
    "Ronaldo",
    "Cristianaldo",
    "Rapier",
    "Spirit",
    "Ghost",
    "Angel",
    "Frank",
    "Cheeseburger",
    "Hotdog",
    "Curiosity",
    "Discovery",
    "Pathfinder",
    "Djikstra"
]
