var NAMES = [
    "Donnager",
    "Pinus Contorta",
    "Tachi",
    "Scipio Africanus",
    "Limiting Factor",
    "Little Rascal",
    "Gunboat Diplomat",
    "Sirenum Scopuli",
    "Don Quixote",
    "International House of Pancakes",
    "Miguel de Cervantes",
    "Fatherly Instinct",
    "Exercise For The Reader",
    "Komrade Kat",
    "Pierre-Simon Laplace",
    "Joseph-Louis Lagrange",
    "Sound of Silence",
    "Null Hypothesis",
    "Maxwell's Demon",
    "New Mombasa",
    "Shadow of Intent",
    "Long Night of Solace",
    "In Amber Clad",
    "Medium Rare",
    "Silkworm",
    "Roberta Draper",
    "Grace Hopper",
    "Iain M. Banks",
    "James S.A. Corey"
]
